server:
  port: 8888

spring:
  flyway:
    enabled: true
    baselineOnMigrate: false
    validate-on-migrate: false
    outOfOrder: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: Reigns@123
  profiles:
    active: dev
  application:
    name: config-server
    label: main
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Srinivas-Maddeboina-12/config-repo.git
          username: ${GitHubUsername}
          password: ${PersonalAccessToken}
          clone-on-start: true
          default-label: main
