server:
  port: 8888

spring:
  profiles:
    active: dev
  application:
    name: config-server
    label: main
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Srinivas-Maddeboina-12/config-repo.git
          clone-on-start: true
          # optional: pick a branch
          default-label: main
